sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - dev

php:
  - 7.0
  - 7.1

cache:
  - composer
  - $HOME/.composer/cache

env:
  global:
    - WP_CLI_BIN_DIR=/tmp/wp-cli-phar

before_script:
  - bash bin/install-package-tests.sh

script: ./vendor/bin/behat
